### ISSUE TITLE
Case sensitive and some functions

### ISSUE THREAD

**Issue by Shkiperon** [peacefixation/vscode-asterisk#3]
Hello.
If I write “PlayBack” instead of “Playback” or “HangUp” instead of “Hangup” in the Asterisk configuration file, these functions will not be highlighted.
Also, the constructions "While" and "EndWhile" will not be highlighted too.

**Comment by peacefixation** [comment]
I'll take a look at supporting those soon @Shkiperon

**Comment by Shkiperon** [comment]
Hello. Do you have some progress about this issue?

**Comment by peacefixation** [comment]
@Shkiperon I've added the While and EndWhile applications. I'm not going to make the highlighter case insensitive, however. I think it's appropriate to match the applications as Asterisk defines them. This change has been published. Sorry for the delay in action and response, it's been a busy few months.
